# Generated by Django 5.2.9 on 2025-12-14 11:51

import django.contrib.postgres.fields
import django.db.models.deletion
import profiles.storages
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "BEGINNER"),
                            ("intermediate", "INTERMEDIATE"),
                            ("advanced", "ADVANCED"),
                            ("native", "NATIVE"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("about", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "MALE"), ("female", "FEMALE")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "military_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("completed", "COMPLETED"),
                            ("pending", "PENDING"),
                            ("not_required", "NOT_REQUIRED"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[("single", "SINGLE"), ("married", "MARRIED")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("picture", models.ImageField(null=True, upload_to="")),
                ("description", models.TextField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ManyToManyField(
                        related_name="profiles", to="locations.location"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("on_site", "ON_SITE"),
                                ("remote", "REMOTE"),
                                ("hybrid", "HYBRID"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "minimum_experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "ENTRY"),
                            ("mid", "MID"),
                            ("senior", "SENIOR"),
                            ("principal", "PRINCIPAL"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "maximum_experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "ENTRY"),
                            ("mid", "MID"),
                            ("senior", "SENIOR"),
                            ("principal", "PRINCIPAL"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "minimum_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usd", "USD"),
                            ("eur", "EUR"),
                            ("irr", "IRR"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(
                        related_name="preferences", to="profiles.language"
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="preferences", to="locations.location"
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferences",
                "verbose_name_plural": "Preferences",
            },
        ),
        migrations.AddField(
            model_name="language",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="languages",
                to="profiles.profile",
            ),
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interest",
                "verbose_name_plural": "Interests",
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("on_site", "ON_SITE"),
                            ("remote", "REMOTE"),
                            ("hybrid", "HYBRID"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("full_time", "FULL_TIME"),
                            ("part_time", "PART_TIME"),
                            ("contract", "CONTRACT"),
                            ("volunteer", "VOLUNTEER"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("school", models.CharField(max_length=255)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("high_school", "HIGH_SCHOOL"),
                            ("bachelor", "BACHELOR"),
                            ("master", "MASTER"),
                            ("doctorate", "DOCTORATE"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=255, null=True)),
                ("field_of_study", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Educations",
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("issued_by", models.CharField(max_length=255)),
                ("issued_date", models.DateField()),
                ("expiration_date", models.DateField(null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Achievement",
                "verbose_name_plural": "Achievements",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation",
                "verbose_name_plural": "Recommendations",
            },
        ),
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research",
                "verbose_name_plural": "Research",
            },
        ),
        migrations.CreateModel(
            name="ResumeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=profiles.storages.ResumeStorage(), upload_to=""
                    ),
                ),
                (
                    "process_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PROCESSING", "PROCESSING"),
                            ("FINISHED", "FINISHED"),
                            ("FAILED", "FAILED"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume File",
                "verbose_name_plural": "Resume Files",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "BEGINNER"),
                            ("intermediate", "INTERMEDIATE"),
                            ("advanced", "ADVANCED"),
                            ("expert", "EXPERT"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LINKEDIN"),
                            ("x", "X"),
                            ("instagram", "INSTAGRAM"),
                            ("facebook", "FACEBOOK"),
                            ("youtube", "YOUTUBE"),
                            ("tiktok", "TIKTOK"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
    ]
