# Generated by Django 5.2.9 on 2026-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="profiles", to="locations.location"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
