# Generated by Django 5.2.9

import django.db.models.deletion
import profiles.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUpload',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'file',
                    models.FileField(
                        storage=profiles.storages.ResumeStorage(), upload_to=''
                    ),
                ),
                (
                    'process_status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'PENDING'),
                            ('PROCESSING', 'PROCESSING'),
                            ('FINISHED', 'FINISHED'),
                            ('FAILED', 'FAILED'),
                        ],
                        default='PENDING',
                        max_length=32,
                    ),
                ),
                (
                    'raw_data',
                    models.JSONField(
                        blank=True, 
                        help_text='Raw extracted data from the resume', 
                        null=True
                    ),
                ),
                (
                    'parsed_data',
                    models.JSONField(
                        blank=True, 
                        help_text='Structured parsed data from AI processing', 
                        null=True
                    ),
                ),
                (
                    'error_message',
                    models.TextField(
                        blank=True, 
                        help_text='Error message if processing failed', 
                        null=True
                    ),
                ),
                (
                    'profile',
                    models.ForeignKey(
                        blank=True,
                        help_text='The profile created from this resume upload',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='resume_uploads',
                        to='profiles.profile',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Resume Upload',
                'verbose_name_plural': 'Resume Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
