# Generated by Django 5.2.9 on 2025-12-14 12:45

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=3072, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Job Category",
                "verbose_name_plural": "Job Categories",
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference_id", models.CharField(max_length=255)),
                ("job_page", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_site", "ON_SITE"),
                            ("remote", "REMOTE"),
                            ("hybrid", "HYBRID"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "FULL_TIME"),
                            ("part_time", "PART_TIME"),
                            ("contract", "CONTRACT"),
                            ("volunteer", "VOLUNTEER"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "ENTRY"),
                            ("mid", "MID"),
                            ("senior", "SENIOR"),
                            ("principal", "PRINCIPAL"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "MALE"),
                            ("female", "FEMALE"),
                            ("any", "ANY"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "military_service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("should_have", "SHOULD_HAVE"),
                            ("should_not_have", "SHOULD_NOT_HAVE"),
                            ("any", "ANY"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "minimum_education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high_school", "HIGH_SCHOOL"),
                            ("bachelor", "BACHELOR"),
                            ("master", "MASTER"),
                            ("doctorate", "DOCTORATE"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "minimum_experience_years",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "minimum_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maximum_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("usd", "USD"),
                            ("eur", "EUR"),
                            ("irr", "IRR"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[("fa", "PERSIAN"), ("en", "ENGLISH")],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="companies.company",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity",
                "verbose_name_plural": "Opportunities",
            },
        ),
    ]
