# Generated by Django 5.2.9 on 2025-12-20 20:57

from django.db import migrations


def create_default_categories(apps, schema_editor):
    JobCategory = apps.get_model("jobs", "JobCategory")

    categories = [
        {
            "name": "Accounting & Finance",
            "description": "Financial stewardship, reporting, and capital management. Examples: Accountant, Financial Analyst, Auditor, Controller, Tax Specialist.",
        },
        {
            "name": "Administrative & Office Support",
            "description": "Administrative coordination and day-to-day office operations. Examples: Administrative Assistant, Executive Assistant, Receptionist, Office Manager.",
        },
        {
            "name": "Architecture & Planning",
            "description": "Design of built environments and long-term spatial planning. Examples: Architect, Urban Planner, Landscape Architect, Architectural Technologist.",
        },
        {
            "name": "Art, Design & Creative Services",
            "description": "Visual and creative production for brands and products. Examples: Graphic Designer, UX Designer, Art Director, Creative Producer.",
        },
        {
            "name": "Aviation & Aerospace",
            "description": "Aircraft operations, maintenance, and aerospace systems work. Examples: Pilot, Aircraft Mechanic, Avionics Technician, Aerospace Engineer.",
        },
        {
            "name": "Business Development & Partnerships",
            "description": "Growth through new opportunities, channels, and strategic alliances. Examples: Business Development Manager, Partnerships Manager, Channel Manager.",
        },
        {
            "name": "Construction & Trades",
            "description": "Building and site-based skilled work delivering physical projects. Examples: Electrician, Plumber, Carpenter, Site Supervisor, Construction Manager.",
        },
        {
            "name": "Consulting & Advisory",
            "description": "Expert advisory services to solve business or technical problems. Examples: Management Consultant, Strategy Consultant, Risk Advisor, Implementation Consultant.",
        },
        {
            "name": "Customer Service & Support",
            "description": "Customer assistance, issue resolution, and service delivery. Examples: Customer Support Specialist, Call Center Agent, Helpdesk Analyst, Client Services Rep.",
        },
        {
            "name": "Data & Analytics",
            "description": "Data collection, modeling, insight generation, and decision support. Examples: Data Analyst, BI Analyst, Data Scientist, Analytics Engineer.",
        },
        {
            "name": "Education & Training",
            "description": "Teaching, learning design, and skills development. Examples: Teacher, Lecturer, Corporate Trainer, Instructional Designer, Academic Coordinator.",
        },
        {
            "name": "Engineering (Non-Software)",
            "description": "Design and delivery of physical systems and infrastructure. Examples: Mechanical Engineer, Electrical Engineer, Civil Engineer, Chemical Engineer.",
        },
        {
            "name": "Entrepreneurship & Small Business",
            "description": "Owning or operating a business across functions and growth stages. Examples: Founder, Co-Founder, General Manager, Small Business Owner.",
        },
        {
            "name": "Facilities, Maintenance & Property Management",
            "description": "Upkeep and operation of buildings, sites, and property portfolios. Examples: Facilities Manager, Maintenance Technician, Building Engineer, Property Manager.",
        },
        {
            "name": "Government & Public Administration",
            "description": "Public sector operations, policy execution, and civic services. Examples: Policy Officer, Program Officer, Civil Servant, Municipal Administrator.",
        },
        {
            "name": "Healthcare - Clinical",
            "description": "Direct patient care and clinical practice roles. Examples: Physician, Nurse, Physiotherapist, Pharmacist, Radiologic Technologist.",
        },
        {
            "name": "Healthcare - Non-Clinical",
            "description": "Operational and administrative roles supporting healthcare delivery. Examples: Practice Manager, Medical Biller, Healthcare Administrator, Care Coordinator.",
        },
        {
            "name": "Hospitality & Tourism",
            "description": "Guest services, travel experiences, and hospitality operations. Examples: Hotel Manager, Front Desk Agent, Tour Guide, Event Coordinator.",
        },
        {
            "name": "Human Resources & Talent",
            "description": "Workforce planning, people operations, and talent development. Examples: Recruiter, HR Business Partner, Compensation Analyst, Learning & Development Specialist.",
        },
        {
            "name": "Information Technology & Infrastructure",
            "description": "IT operations, networks, systems, and end-user computing. Examples: Systems Administrator, Network Engineer, IT Support Specialist, Cloud Administrator.",
        },
        {
            "name": "Legal & Compliance",
            "description": "Legal counsel, regulatory compliance, and governance oversight. Examples: Lawyer, Paralegal, Compliance Officer, Contracts Manager.",
        },
        {
            "name": "Logistics, Supply Chain & Transportation",
            "description": "Movement of goods, inventory planning, and transportation execution. Examples: Supply Chain Planner, Logistics Coordinator, Warehouse Manager, Fleet Manager.",
        },
        {
            "name": "Manufacturing & Production",
            "description": "Making products at scale, including line operations and production leadership. Examples: Production Operator, Production Supervisor, Manufacturing Engineer, Quality Inspector.",
        },
        {
            "name": "Marketing, Communications & PR",
            "description": "Market positioning, demand generation, and communications strategy. Examples: Marketing Manager, Growth Marketer, Communications Specialist, PR Manager.",
        },
        {
            "name": "Media, Entertainment & Sports",
            "description": "Content creation, production, and operations in media and sports. Examples: Producer, Journalist, Video Editor, Sports Operations Coordinator.",
        },
        {
            "name": "Nonprofit & Social Services",
            "description": "Mission-driven programs and community support services. Examples: Program Manager, Social Worker, Case Manager, Community Outreach Coordinator.",
        },
        {
            "name": "Operations & Program Management",
            "description": "Running core processes and delivering cross-functional initiatives. Examples: Operations Manager, Program Manager, Project Manager, PMO Analyst.",
        },
        {
            "name": "Product Management",
            "description": "Defining, building, and improving products to meet user and business needs. Examples: Product Manager, Technical Product Manager, Product Owner, Product Operations Manager.",
        },
        {
            "name": "Purchasing & Procurement",
            "description": "Sourcing goods/services and managing vendors and contracts. Examples: Procurement Specialist, Category Manager, Sourcing Manager, Vendor Manager.",
        },
        {
            "name": "Quality, Safety & Environment",
            "description": "Quality systems, workplace safety, and environmental compliance programs. Examples: QA Manager, QC Technician, EHS Specialist, Safety Officer.",
        },
        {
            "name": "Real Estate",
            "description": "Property sales, leasing, investment, and development activities. Examples: Real Estate Agent, Leasing Manager, Property Developer, Asset Manager.",
        },
        {
            "name": "Research & Science",
            "description": "Scientific research, experimentation, and R&D across disciplines. Examples: Research Scientist, Lab Technician, R&D Engineer, Clinical Research Associate.",
        },
        {
            "name": "Retail & Store Operations",
            "description": "In-store execution, merchandising, and customer-facing retail operations. Examples: Sales Associate, Store Manager, Visual Merchandiser, Inventory Associate.",
        },
        {
            "name": "Sales",
            "description": "Revenue generation through prospecting, closing, and account growth. Examples: Account Executive, Sales Representative, Account Manager, Sales Development Rep.",
        },
        {
            "name": "Security & Protective Services",
            "description": "Protection of people, assets, and information through prevention and response. Examples: Security Officer, Loss Prevention Specialist, Security Analyst, Incident Responder.",
        },
        {
            "name": "Skilled Trades - Technical Services",
            "description": "Field and technical service work installing, maintaining, and repairing equipment. Examples: HVAC Technician, Field Service Engineer, Equipment Technician, Elevator Mechanic.",
        },
        {
            "name": "Software Engineering & Development",
            "description": "Designing and building software applications, platforms, and services. Examples: Software Engineer, Backend Developer, Frontend Developer, Mobile Developer, QA Engineer.",
        },
        {
            "name": "Strategy & Corporate Development",
            "description": "Enterprise strategy, market analysis, and M&A-related execution. Examples: Corporate Strategist, Corporate Development Analyst, M&A Associate, Competitive Intelligence Analyst.",
        },
        {
            "name": "Writing, Editing & Translation",
            "description": "Creating, refining, and localizing written content. Examples: Copywriter, Technical Writer, Editor, Translator, Content Strategist.",
        },
        {
            "name": "Other / General",
            "description": "General roles that do not neatly fit a single category or are highly cross-functional. Examples: Generalist, Assistant, Associate, Coordinator (varies by organization).",
        },
    ]

    for category_data in categories:
        JobCategory.objects.create(name=category_data["name"], description=category_data["description"])


def remove_default_categories(apps, schema_editor):
    JobCategory = apps.get_model("jobs", "JobCategory")
    category_names = [
        "Accounting & Finance",
        "Administrative & Office Support",
        "Architecture & Planning",
        "Art, Design & Creative Services",
        "Aviation & Aerospace",
        "Business Development & Partnerships",
        "Construction & Trades",
        "Consulting & Advisory",
        "Customer Service & Support",
        "Data & Analytics",
        "Education & Training",
        "Engineering (Non-Software)",
        "Entrepreneurship & Small Business",
        "Facilities, Maintenance & Property Management",
        "Government & Public Administration",
        "Healthcare - Clinical",
        "Healthcare - Non-Clinical",
        "Hospitality & Tourism",
        "Human Resources & Talent",
        "Information Technology & Infrastructure",
        "Legal & Compliance",
        "Logistics, Supply Chain & Transportation",
        "Manufacturing & Production",
        "Marketing, Communications & PR",
        "Media, Entertainment & Sports",
        "Nonprofit & Social Services",
        "Operations & Program Management",
        "Product Management",
        "Purchasing & Procurement",
        "Quality, Safety & Environment",
        "Real Estate",
        "Research & Science",
        "Retail & Store Operations",
        "Sales",
        "Security & Protective Services",
        "Skilled Trades - Technical Services",
        "Software Engineering & Development",
        "Strategy & Corporate Development",
        "Writing, Editing & Translation",
        "Other / General",
    ]
    JobCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
