# Generated by Django 5.2.9 on 2025-12-17 12:37

import companies.storages
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Perk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=3072, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "Perk",
                "verbose_name_plural": "Perks",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=3072, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("ai_summary", models.TextField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("page", models.URLField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=companies.storages.CompanyLogoStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "SMALL"),
                            ("medium", "MEDIUM"),
                            ("large", "LARGE"),
                            ("entreprise", "ENTREPRISE"),
                            ("other", "OTHER"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies",
                        to="locations.location",
                    ),
                ),
                (
                    "perks",
                    models.ManyToManyField(
                        related_name="companies", to="companies.perk"
                    ),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
                "ordering": ["-created_at"],
            },
        ),
    ]
