# Generated by Django 5.2.9 on 2025-12-17 12:37

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(dimensions=3072, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("global", "GLOBAL"),
                            ("continent", "CONTINENT"),
                            ("country", "COUNTRY"),
                            ("city", "CITY"),
                            ("district", "DISTRICT"),
                            ("neighborhood", "NEIGHBORHOOD"),
                            ("street", "STREET"),
                            ("building", "BUILDING"),
                            ("room", "ROOM"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-created_at"],
                "unique_together": {("name", "level")},
            },
        ),
    ]
